language: python
python:
  - "2.7"
addons:
    apt:
        packages:
        - python-pygame
install:
    - git clone -b develop https://github.com/gragas/buffalo/
    - cd buffalo && python setup.py develop
    - cd ..
    - pip install -r .travis_requirements.txt
script: 
    - nosetests
virtualenv:
    system_site_packages: true